### PR TITLE
Add new endpoint for getting annotations for a specific platformVersion.

### PR DESCRIPTION
**Pull request by BerniVarga**
Changes made:
- added new endpoint /content/{uuid}/annotations/{platformVersion} -> returns annotations for a specific platformVersion. The format of the annotations will be enriched with all the existing identifier fields, and the platformVersion field.
- switched to govendor (from godep)
- updated the annotations-rw version in the godep file
- adjusted the tests to the new version of the annotations-rw
- updated README
Tested in XP.

### CODE REVIEW

**Comment by kovacshuni** [comment]
`filteredRead` and `read`
and
`GetAnnotations` and `GetFilteredAnnotations` are very similar, i think you could merge them in one generic method.

third opinion @tosan88 @scott-ace-newton ?

**Comment by BerniVarga** [comment]
Re: `GetAnnotations` vs `GetFilteredAnnotations` - I think it is more readable and clear to have a separate handler for each of the endpoints. On the other hand, `GetFilteredAnnotations` is internal, `GetAnnotations` is used by enrichedContent (public). They return different payload as well. 
Using a generic will make it complicated to do a change only for one endpoint - if needed. 
Even though we would get rid of some code duplication, I don't really see it useful here.

**Comment by scott-ace-newton** [comment]
I can see what Huni means about the code being very similar, however due to the circumstances that Bernie mentioned I think refactoring in this case would do more harm than good

**Comment by kovacshuni** [comment]
okay

**Pull request merged**
